olives/urls.py
from django.urls import path
from django.contrib import admin
from olives import views

app_name = "olives"

urlpatterns = [
    path("", views.index, name="index"),  # The index is the home page of the website
    path('about-us/', views.about_us, name='about-us'),  
    path('gallery/', views.gallery, name='gallery'),
    path("booking/", views.booking, name="booking"),

    path('special-events/', views.specialEvents, name='special-events'),
    path("review-dish/", views.dishReview, name="dishReview"),
    path("staff-sign-up/", views.staffSignUp, name="staffSignUp"),
    path('admin/', admin.site.urls, name="admin"),
    path("add-dish/", views.add_dish, name="add_dish"),
    path("delete-dish/", views.delete_dish, name="delete_dish"),
    path("staff-register/", views.staffSignUp, name="staff_signup"),
    path("staff/", views.staffData, name="staff"),
    path('contact-us/', views.emailView, name='contact-us'),

    path("menu/", views.menu, name="menu"),
    path("review/", views.reviewRest, name="review-rest"),
    path("confirm-booking/", views.confirmBooking, name="confirm-booking"),

]

olivesProject/urls.py
from django.contrib import admin
from django.urls import path, include
from olives import views
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('', include("olives.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    path('contact-us/',views.emailView, name='email'),
    path('success/', views.successView, name='success'),
]

olives/models.py
import os  # Needed to use the os.path function

from django.db import models  # Needed to uses django models
from django.template.defaultfilters import slugify  # Needed to uses the slugify function
from django.contrib.auth.models import User, AbstractUser  # Needed to create a 1 to 1 link with the django built in


# User model


class Menu(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    slug = models.CharField(max_length=50, null=True)
    # Note in the database only the stores the url to these items and not the items themselves
    # Note it will store it in the MEDIA/ folder
    image = models.ImageField(upload_to=os.path.join("menus", "images"))
    file = models.FileField(upload_to=os.path.join("menus", "files"))

    def save(self, *args, **kwargs):  # save method is always called when creating or updating an instance of Django
        # model
        self.slug = slugify(self.name)  # slugify creates a url safe name by removing the spaces for dashes
        super(Menu, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Menus'

# Contains the reviews provided by the users and staff.
class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.CharField(max_length=500)
    score = models.IntegerField(default=50)

    class Meta:
        verbose_name_plural = 'Review'    

# Contains all the dishes provided by the restaurant.
class Dish(models.Model):
    name = models.CharField(max_length=50)  # The name of the dish
    likes = models.IntegerField(default=0)  # The number of likes the dishes have

    class Meta:
        verbose_name_plural = 'Dishes'

    def __str__(self):
        return self.name

# Keeps track of the users and the dishes liked by them.
class LikedDish(models.Model):
    userID = models.IntegerField(default=0)
    dishID = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'LikedDish'

# Order has a many to many relationship with dishes
class Order(models.Model):
    orderId = models.CharField(max_length=64)
    dishes = models.ManyToManyField(Dish)  # Creates the many to many link with the dishes table

    class Meta:
        verbose_name_plural = 'Orders'

    def __str__(self):
        return self.orderId


# Order has many to 1 relationship with Customer
class Customer(models.Model):
    # This line is required as it links user profile to a user model instance.
    customer = models.OneToOneField(User, on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = 'Customers'

    def __str__(self):
        return self.customer


class Staff(models.Model):
    staff = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    is_staff = True
    staff_list = User.objects.all()

    class Meta:
        verbose_name_plural = 'Staff'

    def __str__(self):
        return self.staff

class Admin(models.Model):
    admin = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    admin_check = models.ForeignKey(Staff, on_delete=models.CASCADE)
    is_admin = True

# Booking no longer has a link to any other table
class Booking(models.Model):
    name = models.CharField(max_length=128, default="")
    email = models.EmailField(default="")
    phone = models.CharField(max_length=15)
    noOfPeople = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()
    confirm = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Bookings'

    def __str__(self):
        return self.name

olives/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from olives.models import Dish, Booking, Review
from datetime import datetime
from django.utils import timezone
from static.ML.review.reviewModel import use_model

class StaffSignUpForm(UserCreationForm):
    username = forms.CharField(max_length=20, required=True)
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254)
    is_staff = True
    class Meta:
        model = User
        fields = ('username', "first_name", "last_name", 'email', 'password1', 'password2', "is_staff")

class ReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea)
    score = forms.IntegerField(widget = forms.HiddenInput(), required=False)
    class Meta:
        model = Review
        fields = ('review',)
    

class DishForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = ('name',)

    def clean(self):
        data = self.cleaned_data
        name = data.get('name')
        # to check for unique dishes
        if (Dish.objects.filter(name__icontains=name)):
            self.add_error('name', 'Dish already exists!')


class BookingForm(forms.ModelForm):
    # For the booking form doesnt have the confirm field as that is always set to false initially
    name = forms.CharField(max_length=128, help_text="Name")
    email = forms.EmailField(help_text="Email Address")
    phone = forms.CharField(max_length=15, help_text="Phone Number")
    noOfPeople = forms.IntegerField(help_text="Number of People")

    date = forms.DateField(help_text="Date")

    date = forms.DateField(widget=forms.SelectDateWidget, help_text="Date")

    time = forms.TimeField(help_text="Time")

    class Meta:
        model = Booking
        fields = ("name", "phone", "noOfPeople", "date", "time")

    
    def clean(self):
        data = self.cleaned_data
        if(data['noOfPeople']<=1):
            self.add_error('noOfPeople', "People cannot be 0 or negative")
        if data['date'] < timezone.now().date():
            self.add_error('date',"Date cannot be in the past!")
        elif data['date'] == timezone.now().date() and data['time'] < datetime.now().time():
            self.add_error('time',"Time cannot be in past!")
        


class DishDeleteForm(forms.Form):
    dishDelete = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        super(DishDeleteForm, self).__init__(*args, **kwargs)

        self.fields['dishDelete'] = forms.ChoiceField(choices=[(dish.id,dish.name) for dish in Dish.objects.all() ],help_text="Select Dish to Delete")

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

olives/views.py
from django.http import HttpResponse, HttpResponseRedirect

from olives.forms import StaffSignUpForm, BookingForm
from olives.models import Dish, Staff

from olives.forms import StaffSignUpForm, BookingForm, ReviewForm
from olives.models import Dish, Staff, Review, Booking, LikedDish

from olives.forms import DishForm, DishDeleteForm, ContactForm
from django.contrib import messages
from django.views import View
from django.contrib.auth import authenticate, login
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.hashers import make_password  # This is to allow encryption of the passwords.
from static.ML.review import reviewModel
from static.ML.review.reviewModel import use_model

def index(request):
	return render(request, "olives/index.html")


def about_us(request):
	return render(request, "olives/about-us.html")


# This checks if the user is a staff member.
def staff_check(user):
	return user.is_authenticated and user.is_staff


def gallery(request):
	return render(request, "olives/gallery.html")


def specialEvents(request):
	return render(request, "olives/special-events.html")


# This is available to all logged in users.
@login_required


# This is available to all logged in users.
# This allows custom testss

def dishReview(request):
	# Adds 1 when button is clicked, to the likes variable of the dish object.
	# The second if condition checks whether the user has already liked the dish.
	if request.method == 'POST':
		dishId = request.POST['dish-id']
		dish = Dish.objects.filter(id=dishId).first()
		if LikedDish.objects.filter(userID=request.user.id, dishID=dishId).exists()==False:
			dish.likes += 1
			dish.save()
			likeUser = LikedDish()
			likeUser.dishID = dishId
			likeUser.userID = request.user.id
			likeUser.save()

	dishList = Dish.objects.order_by('-likes')[:5]
	allDishList = Dish.objects.all()
	context_dict = {}
	context_dict['boldmessage'] = 'The top five dishes of Olives & Pesto:'
	context_dict['TopDishes'] = dishList
	context_dict['AllDishes'] = allDishList
	response = render(request, "olives/reviewDishes.html", context=context_dict)
	return response


# This is for the admin(s) only
@login_required
def reviewRest(request):
	review = Review.objects.all()
	context_dict = {'userReviews': review}
	if request.method == 'POST':
		form = ReviewForm(request.POST)
		if form.is_valid():
			form.instance.user = request.user
			score = use_model(form.instance.review)
			form.instance.score = score
			form.save(commit=True)
			return HttpResponseRedirect(reverse('olives:review-rest'))
		else:
			print(form.errors)
	else:
		form = ReviewForm()
	context_dict.update({"form": form})
	return render(request, 'olives/review.html', context=context_dict)


# This is for the admin(s) only
@user_passes_test(staff_check)

def add_dish(request):
	if request.method == 'POST':
		form = DishForm(request.POST)
		if form.is_valid():
			form.save(commit=True)
			return HttpResponseRedirect(reverse('olives:add_dish'))
		else:
			print(form.errors)
	else:
		form = DishForm()
	return render(request, 'olives/add_dish.html', {'form': form})


# This is for the admin(s) only.
@login_required


# This is for the admin(s) only.
@user_passes_test(staff_check)

def delete_dish(request):
	if request.method == 'POST':
		form = DishDeleteForm(request.POST)
		if form.is_valid():
			dishID = form.cleaned_data.get('dishDelete')
			dish = Dish.objects.filter(id=dishID).first().delete()
			return HttpResponseRedirect(reverse('olives:delete_dish'))
		else:
			print(form.errors)
	else:
		form = DishDeleteForm()
	return render(request, 'olives/delete_dish.html', {'form': form})

def staffSignUp(request):
	if request.method == 'POST':
		form = StaffSignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			# Encrypting the password using Argon2 before storing it
			raw_password = form.cleaned_data.get('password1')
			hashed_password = make_password(raw_password)
			user = authenticate(username=username, password=hashed_password)
			# login(request, user)
			return redirect("olives:index")
	else:
		form = StaffSignUpForm()
	return render(request, 'olives/staffRegister.html', {'form': form})


# This is for Admins and SUPERUSERS only.
@login_required


# This is for Admins and SUPERUSERS only.
@user_passes_test(staff_check)

def staffData(request):
	user_list = User.objects.all()
	context_dict = {}
	context_dict['users'] = user_list
	return render(request, 'olives/staff.html', context=context_dict)


def booking(request):
	form = BookingForm()

	if request.method == "POST":
		form = BookingForm(request.POST)
		if form.is_valid():
			form.save(commit=True)
			# Sets up Email details
			mail_subject = "Booking Request Received"
			mail_body = "A booking request has been received with the following details a confirmation email will be " \
						"sent shortly. " + "\n" \
						+ "Name: " + form.cleaned_data.get("name") + "\n" \
						+ "Phone: " + form.cleaned_data.get("phone") + "\n" \
						+ "Number of People: " + str(form.cleaned_data.get("noOfPeople")) + "\n" \
						+ "Date: " + str(form.cleaned_data.get("date")) + "\n" \
						+ "Time: " + str(form.cleaned_data.get("time")) + "\n"
			mail_sender = "Booking@olivesandpesto.com"
			mail_sendAddress = form.cleaned_data.get("email")
			# Send Mail takes 4  required parameters - Subject Line, Message Body, Sender Address, Send Address
			send_mail(mail_subject, mail_body, mail_sender, [mail_sendAddress], fail_silently=False)
			return redirect("olives:index")
		else:
			print(form.errors)

	return render(request, "olives/booking.html", {'form': form})




def emailView(request):
	if request.method == 'GET':
		form = ContactForm()
	else:
		form = ContactForm(request.POST)
		if form.is_valid():
			subject = form.cleaned_data['subject']
			from_email = form.cleaned_data['from_email']
			message = form.cleaned_data['message']
			try:

				send_mail(subject, message, from_email, ['olivesandpesto1234@gmail.com'])
			except BadHeaderError:
				return HttpResponse('Invalid header found.')
			return redirect('success')
	return render(request, "olives/contactus.html", {'form': form})

def successView(request):
	return redirect("olives:index")


def menu(request):
	return render(request, "olives/menu.html")


@user_passes_test(staff_check)
def confirmBooking(request):
	if request.method == 'POST':
		# Updates database
		bookingId = request.POST['confirm-booking']
		booking = Booking.objects.filter(id=bookingId).first()
		booking.confirm = True
		booking.save()
		# sends booking confirmation
		mail_subject = "Booking Request Confirmed"
		mail_body = "We have confirmed a booking with the following details " + "\n" \
					+ "Name: " + booking.name + "\n" \
					+ "Phone: " + booking.phone + "\n" \
					+ "Number of People: " + str(booking.noOfPeople) + "\n" \
					+ "Date: " + str(booking.date) + "\n" \
					+ "Time: " + str(booking.time) + "\n"
		mail_sender = "Booking@olivesandpesto.com"
		mail_sendAddress = booking.email
		# Send Mail takes 4  required parameters - Subject Line, Message Body, Sender Address, Send Address
		send_mail(mail_subject, mail_body, mail_sender, [mail_sendAddress], fail_silently=False)


	bookings = Booking.objects.order_by('time')
	context_dict = {}
	context_dict['bookings'] = bookings
	return render(request, "olives/confirm-booking.html", context=context_dict)

templates/olives/add_dish.html
{% extends "olives/base.html" %}
{% load staticfiles %}


{% block title_block %}
    Add Dish
{% endblock %}

{% block body_block %}
<main class="page contact-us-page">
    <section class="clean-block clean-form dark">
        <div class="container">
            <div class="block-heading">
                <h2 class="text">Add a Dish</h2>
            </div>

            <form class="form" id="dish_form" method="post" action="{% url "olives:add_dish" %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                <div class="form-group">
                    <label>
                        {{ field.label }}
                    </label>
                    {{ field }}
                {{ field.errors }}
                </div>
                {% endfor %}
                <input class="btn btn-outline-light btn-lg btn-form center" type="submit" name="submit" value="Add Dish" />
                <button class="btn btn-outline-light btn-lg center"><a href="{% url "olives:dishReview" %}">To the review page!</a></button>
            </form>


        </div>
    </section>
</main>
{% endblock %}

templates/olives/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="icon" href="{% static "img/favicon.png" %}">
    <title>

    Olives | {% block title_block %} <!--Enter the title here once the base file is inherited -->
    {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="{% static "fonts/simple-line-icons.min.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="{% static "css/smoothproducts.css" %}">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar">
        <div class="container"><a class="navbar-brand logo" href="{% url "olives:index" %}">Olives & Pesto</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1" >
                <ul class="nav navbar-nav ml-auto">
                <!--Displays name if user is logged in  -->
                <!-- IF logged in and staff shows that you have staff status -->
                    {% if user.is_authenticated %}
                        <li class="nav-item" role="presentation"><a class="nav-link">Logged In: {{ user.username }}
                        {% if user.is_staff %}
                            <br>    STAFF
                        {% else %}
                            <br>    USER
                        {% endif %}
                        </a></li>
                    {% else %}
                        <li class="nav-item" role="presentation">
                            <a class="nav-link">Not logged in </a>
                        </li>
                    {% endif %}
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url "olives:index" %}">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url "olives:about-us" %}">About Us</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url "olives:menu" %}">Menu</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url "olives:gallery" %}">Gallery</a></li>
                    {% if user.is_authenticated %}
                        <li class="nav-item" role="presentation"><a class="nav-link" role="presentation" href="/accounts/logout">Logout</a></li>
                    {% else %}
                        <li class="nav-item" role="presentation"><a class="nav-link" href="/accounts/login">Login</a></li>
                    {% endif %} 
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url "olives:special-events" %}">Events</a></li>
                    <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="true" href="#">More</a>
                        <div class="dropdown-menu" role="menu">
                            <a class="dropdown-item" role="presentation" href="/accounts/register">Register</a>
                            <a class="dropdown-item" role="presentation" href="{% url 'olives:contact-us' %}">Contact Us</a>
                            <a class="dropdown-item" role="presentation" href="{% url "olives:dishReview" %}">Review Dish</a>
                            <a class="dropdown-item" role="presentation" href="{% url "olives:review-rest" %}">Review Resturant</a>
                            <a class="dropdown-item" role="presentation" href="{% url "olives:booking" %}">Book a table</a>
                            {% if user.is_authenticated %}
                                <a class="dropdown-item" role="presentation" href="/staff-register">Staff-Register</a>
                            {% endif %}
                            <a class="dropdown-item" role="presentation" href="{% url "olives:contact-us" %}">Contact Us</a>
                            {% if user.is_staff %}
                                <a class="dropdown-item" role="presentation" href="{% url "olives:confirm-booking" %}">Confirm Booking</a>
                                <a class="dropdown-item" role="presentation" href="{% url "olives:add_dish" %}">Add Dish</a>
                                <a class="dropdown-item" role="presentation" href="{% url "olives:delete_dish" %}">Delete Dish</a>
                            {% endif %}

                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block body_block %}
        <!--Should be completed when inherited -->
    {% endblock %}

    <footer class="page-footer dark">
        <footer class="page-footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4 text-center">
                        <h5>
                            Opening Times <br>
                            Mon - Thurs: 12-3 pm, 5 - 10pm. <br>
                            Fri - Sat: 12-3pm, 5-10:30pm. <br>
                            Sun: 5-10pm <br>
                        </h5>
                    </div>
                    <div class="col-sm-4 text-center">
                        <h5>
                            Contact us <br>
                            customersupport@ olivesandpesto.com <br>
                        </h5>
                    </div>
                    <div class="col-sm-4 text-center">
                        <h5>
                            Social media <br>
                            Facebook <br>
                            Twitter <br>
                            Instagram <br>
                        </h5>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <p>© 2020 Copyright Text</p>
            </div>
        </footer>
    </footer>
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="{% static "js/smoothproducts.min.js" %}"></script>
    <script src="{% static "js/theme.js" %}"></script>
</body>

</html>

templates/olives/booking.html
{% extends 'olives/base.html' %}
{% load static %}

{% block title_block %}
Booking
{% endblock %}

{% block body_block %}
<main class="page contact-us-page">
    <section class="clean-block clean-form dark">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text">Booking</h2>
                    <p>To Make a booking fill the form bellow. </p>
                </div>
                <form class="form" id="dish_form" method="post" action="/booking/">
                    {% csrf_token %}
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>
                            {{ field.help_text }}
                        </label>
                    {{ field }}
                    {{ field.errors }}
                    </div>
                    {% endfor %}
                    <button class="btn btn-outline-light btn-lg btn-form center" type="submit" name="submit" value="Make Booking">Send</button>
                </form>
            </div>
    </section>
</main>
{% endblock %}

templates/olives/confirm-booking.html
{% extends 'olives/base.html' %}

{% block title_block %}
    Confirm Booking
{% endblock %}

{% block body_block %}

<main class="page contact-us-page">
    <section class="clean-block dark">
        <div class="container">
            <div class="block-heading">
                <h2 class="text">Confirm Booking</h2>
            </div>

            {% if bookings %}
                <h3 class="text-center">Confirmed Bookings</h3>
                {% for booking in bookings %}
                    {% if booking.confirm == True %}
                        <p class="text-center"> Name: {{ booking.name }} Date: {{ booking.date }} Time: {{ booking.time }}</p>
                    {% endif %}
                {% endfor %}

                <h3 class="text-center">Unconfirmed Bookings</h3>
                {% for booking in bookings %}
                    {% if booking.confirm == False %}
                        <p class="text-center"> Name: {{ booking.name }} Date: {{ booking.date }} Time: {{ booking.time }}</p>
                        <form action="{% url "olives:confirm-booking" %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="confirm-booking" value={{ booking.id }}>
                            <button class="btn btn-outline-light btn-sm btn-like" type="submit">Confirm</button>
                        </form>
                    {% endif %}
                {% endfor %}

            {% else %}
                <p class="text-center"><strong>There are no Bookings to Confirm</strong></p><br>
            {% endif %}

        </div>
    </section>
</main>
{% endblock %}

templates/olives/contactus.html
{% extends 'olives/base.html' %}


{% block title_block %}
    Contact Us
{% endblock %}

{% block body_block %}
<main class="page contact-us-page">
    <section class="clean-block clean-form dark">
        <div class="container">
            <div class="block-heading">
                <h2 class="text">Contact Us</h2>
            </div>




                <form class="form" method="post" id="contact_form">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div class="form-group"><button class="btn btn-outline-light btn-lg btn-form center" type="submit">Send</button></div>

            </form>
        </div>
        </div>



    </section>
</main>
{% endblock %}

templates/olives/delete_dish.html
{% extends 'olives/base.html' %}

{% block title_block %}
    Delete A Dish
{% endblock %}

{% block body_block %}
<main class="page contact-us-page">
    <section class="clean-block clean-form dark">
        <div class="container">
            <div class="block-heading">
                <h2 class="text">Delete a Dish</h2>
            </div>

            <form class="form" id="delete_dish_form" method="post" action="{% url "olives:delete_dish" %}">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                <div class="form-group">
                    <label>
                        {{ field.help_text }}
                    </label>
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <input class="btn btn-outline-light btn-lg btn-form center" type="submit" name="submit" value="Delete Dish" />
                <button class="btn btn-outline-light btn-lg center"><a href="{% url "olives:dishReview" %}">To the review page!</a></button>
            </form>
        </div>
    </section>
</main>
{% endblock %}

templates/olives/index.html
{% extends 'olives/base.html' %} 
{% load static %} 

{% block title_block %}
Home
{% endblock %}

{% block body_block %}
<   <main class="page">
        <section class="clean-block index dark">
            <div class="container">
                <div class="row justify-content-center">
                	<img src="{% static "img/main-food/restaurant1.jpg" %}" class="img-fluid" alt="Responsive image">
                </div>
                <div class="text centered mt-5">
                <h3 class="display-4">Olives and Pesto</h3>
                <p class="font-weight-light">The finest in Mexitalian dining.</p> 
            	</div>
            </div>
        </section>
    </main>
{% endblock %}

templates/olives/reviewDishes.html
{% extends 'olives/base.html' %}
# Only LOGGED IN can access
{% block title_block %}        
    Dish Review Page
{% endblock %}
        
{% block body_block %}
<main class="page contact-us-page" xmlns="http://www.w3.org/1999/html">
    <section class="clean-block dark">
        <div class="container">
            <div class="block-heading">
                <h2 class="text">Review Dishes</h2>
            </div>

            <h3 class="text-center">{{ boldmessage }}</h3>
            {% if TopDishes %}
                {% for dish in TopDishes %}
                    <p class="text-center">{{ dish.name }}<strong> Likes: </strong>{{ dish.likes }}</p>
                {% endfor %}
            {% else %}
                <p class="text-center"><strong>There are no dishes present!</strong></p><br>
            {% endif %}
            {% if user.is_authenticated %}
            <h3 class="text-center">Dishes to Review</h3>
            {% if AllDishes %}
                {% for dish in AllDishes %}
                <p class="text-center">
                    {{ dish.name }}: <Strong id="like_count">{{ dish.likes }}</Strong> likes
                    <form action="{% url "olives:dishReview" %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="dish-id" value={{ dish.id }}>
                        {% if not user.is_staff %}
                            <button class="btn btn-outline-light btn-sm btn-form" type="submit">Add Like</button>
                        {% endif %}
                    </form>
                    <br>
                </p>
                {% endfor %}
                {% if user.is_staff %}
                    <p class="text-center">Only Customers are allowed to rate dishes.</p>
                {% endif %} 
            {% else %}
                <p class="text-center"><strong>There are no dish present.</strong></p>
            {% endif %}
            

            <a href="{% url "olives:add_dish" %}"> <button class="btn btn-outline-light btn-lg btn-form center">Add a dish!</button> </a>
            <a href="{% url "olives:delete_dish" %}"> <button class="btn btn-outline-light btn-lg btn-form center">Delete a dish!</button> </a>
            {% endif %}
        </div>
    </section>
</main>
{% endblock %}